# dummy config.yml please research flexget.com for correct config file format
web_server:
  bind: 0.0.0.0
  port: 3539
api: yes
webui: yes

tasks:
  taskname:
    rss: http://example.com/torrents.xml
    series:
      - some open source tv series 1
      - some open source tv series 2
    download: /data
